#!/usr/bin/env python3
"""Regenerate ``src/wifit3/bluetooth/member_uuids.py`` from the Bluetooth SIG member UUID list.

Usage:
    uv run python scripts/generators/gen_bluetooth_member_uuids.py                  # download
    uv run python scripts/generators/gen_bluetooth_member_uuids.py member_uuids.yaml
"""
from __future__ import annotations

import re
import sys
import urllib.request
from pathlib import Path

_URL = ("https://bitbucket.org/bluetooth-SIG/public/raw/main/"
        "assigned_numbers/uuids/member_uuids.yaml")

_OUT = (Path(__file__).resolve().parents[2]
        / "src" / "wifit3" / "bluetooth" / "member_uuids.py")

_ENTRY = re.compile(r'^\s*-\s*uuid:\s*0x([0-9A-Fa-f]{4})\s*\n\s*name:\s*(.+?)\s*$', re.MULTILINE)


def _unquote(name: str) -> str:
    if len(name) >= 2 and name[0] == name[-1] and name[0] in "\"'":
        return name[1:-1]
    return name


def main() -> None:
    if len(sys.argv) > 1:
        text = Path(sys.argv[1]).read_text(encoding="utf-8")
    else:
        with urllib.request.urlopen(_URL, timeout=30) as response:
            text = response.read().decode("utf-8")

    owners = {uuid.lower(): _unquote(name) for uuid, name in _ENTRY.findall(text)}
    if not owners:
        raise SystemExit("no member UUIDs found; the source format may have changed")

    lines = [
        '"""Bluetooth SIG member UUID owners. Generated by '
        'scripts/generators/gen_bluetooth_member_uuids.py."""',
        "",
        "MEMBER_UUID_OWNERS = {",
    ]
    lines += [f"    {uuid!r}: {owners[uuid]!r}," for uuid in sorted(owners)]
    lines += ["}", ""]
    _OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {len(owners)} member UUIDs to {_OUT}")


if __name__ == "__main__":
    main()
